project_id = "qselmijdcggthggjvdej"

[functions.send-telegram]
verify_jwt = false

[functions.telegram-bot-webhook]
verify_jwt = false

[functions.notify-new-listing]
verify_jwt = false

[functions.wayforpay-payment]
verify_jwt = false

[functions.wayforpay-callback]
verify_jwt = false
